spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cuitalk?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.fgcui.blog: info

  file: log/blog.log
server:
  port: 8081